### ISSUE TITLE
Logging panic

### ISSUE THREAD

**Issue by asmaloney** [tliron/glsp#6]
After a `panic` the first time I tried to do anything basic, I read through issue #2 and see that we need to call `logging.Configure()` somewhere, but when I try that I get a different panic:
```go
func main() {
	logging.Configure(1, nil)
...
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1098a03]

goroutine 1 [running]:
github.com/tliron/kutil/logging.Configure(...)
	vendor/github.com/tliron/kutil/logging/api.go:15
main.main()
	main.go:22 +0x83
```

Looking at the [logging implementation](https://github.com/tliron/kutil/blob/main/logging/api.go), it seems like `SetBackend()` needs to be called somewhere as well? I'm not seeing where it is called in puccini.

Thanks!

**Comment by tliron** [comment]
I know that documentation is severely lacking right now. :( But what you do is need to do is add a backend implementation in your imports. Example:
```
import (
    _ "github.com/tliron/kutil/logging/simple"
)
```

**Comment by asmaloney** [comment]
Thanks Tal!
